name: GitHub 3D Contributions

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Prajjwal-Verma
      - run: git config user.email "actions@github.com" && git config user.name "GitHub Actions"
      - run: git add -A && git diff-index --quiet HEAD || git commit -m "update 3d contrib graph"
      - run: git push
